name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: FOR %v IN (glsl/*.comp) DO glslc "glsl/%v" -o "glsl/%v.spv" --target-env=vulkan1.1
    - name: Validate
      run: FOR %v IN (glsl/*.spv) DO spirv-val "glsl/%v"
