name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build GLSL
      shell: bash
      run: for file in glsl/*.comp; do ./glslc.exe "$file" -o "glsl/$(basename "$file" .comp).spv" --target-env=vulkan1.1; done 
    - name: Validate GLSL
      shell: bash
      run: for file in glsl/*.spv; do ./spirv-val.exe "$file"; done 
    - name: Run tests
      run: cargo test
